### ISSUE TITLE
你好 type='time'时，可以添加一个控制显不显示秒那一栏的变量不？...

### ISSUE THREAD

**Issue by snow0119** [wangweianger/zane-data-time-calendar#15]

**Comment by wangweianger** [comment]
@snow0119 你好非常感谢你的建议！ 经过业务需求考虑之后新增了 showsecond 参数来控制是否支持选择秒，请参考文档和demo进行配置 (支持双选择器)。 thinks.

**Comment by wangweianger** [comment]
![01](https://user-images.githubusercontent.com/16434497/55229117-0d488680-5257-11e9-99eb-700c2befb4f9.jpg)

**Comment by snow0119** [comment]
已经看到，可正常使用。谢谢啦~
